// @ts-check
import { useJsonFetch } from './useJsonFetch'

/**
 * Load the real municipal budget snapshot scraped from CONPREL (MinHac).
 * Data is generated by `npm run scrape:budget` → public/data/budget.json.
 */
export function useBudget() {
  return useJsonFetch('/data/budget.json')
}

export function formatEuros(amount, opts = {}) {
  const { compact = false, maximumFractionDigits = 0 } = opts
  if (compact && Math.abs(amount) >= 1_000_000) {
    return `€${(amount / 1_000_000).toFixed(1).replace('.', ',')}M`
  }
  if (compact && Math.abs(amount) >= 1_000) {
    return `€${Math.round(amount / 1_000)}k`
  }
  return new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits,
  }).format(amount)
}

// Canonical colour per expense chapter (for the Donut / BudgetBars components).
export const EXPENSE_COLORS = [
  '#2463EB', // 1 Personal
  '#16A34A', // 2 Bienes corrientes
  '#F59E0B', // 3 Gastos financieros
  '#7C3AED', // 4 Transferencias corrientes
  '#8B5CF6', // 5 Fondo contingencia
  '#DB2777', // 6 Inversiones reales
  '#06B6D4', // 7 Transferencias capital
  '#A16207', // 8 Activos financieros
  '#64748B', // 9 Pasivos financieros
]

export const PROGRAM_COLORS = [
  '#64748B', // Deuda pública
  '#2463EB', // Servicios públicos básicos
  '#16A34A', // Protección y promoción social
  '#F59E0B', // Bienes públicos preferentes
  '#7C3AED', // Actuaciones carácter económico
  '#06B6D4', // Actuaciones carácter general
]
