// @ts-check
import { useEffect, useState } from 'react'

/**
 * Load the real corporación-municipal roster scraped from ribarroja.es.
 * Data is generated by `npm run scrape:officials` → public/data/officials.json.
 */
export function useOfficials() {
  const [state, setState] = useState({
    loading: true,
    error: null,
    data: null,
  })

  useEffect(() => {
    let cancelled = false
    fetch('/data/officials.json', { cache: 'no-cache' })
      .then((r) => {
        if (!r.ok) throw new Error(`officials.json returned ${r.status}`)
        return r.json()
      })
      .then((data) => {
        if (!cancelled) setState({ loading: false, error: null, data })
      })
      .catch((err) => {
        if (!cancelled) setState({ loading: false, error: err, data: null })
      })
    return () => {
      cancelled = true
    }
  }, [])

  return state
}

// Party brand colors, tuned so white text at ≥9px bold meets WCAG AA (≥4.5:1).
// The original brand values fail contrast; these are the darkened AA-safe variants
// used in Spanish political press for print.
export const PARTY_COLORS = {
  PSOE: '#D01832',
  PP: '#2463EB',
  VOX: '#3A8018',
  'Compromís': '#A06116',
  Ciudadanos: '#B05A10',
  Otro: '#6D3FE5',
}

export function partyColor(party) {
  return PARTY_COLORS[party] || '#64748B'
}
