// @ts-check
import { useJsonFetch } from './useJsonFetch'

/**
 * Load the real corporación-municipal roster scraped from ribarroja.es.
 * Data is generated by `npm run scrape:officials` → public/data/officials.json.
 */
export function useOfficials() {
  return useJsonFetch('/data/officials.json')
}

// Canonical palette lives in lib/party-colors (shared with usePromises'
// PARTY_TONE alias); re-exported here because pages historically import
// partyColor from this hook.
export { PARTY_COLORS, partyColor } from '../lib/party-colors'
