import { useEffect, useState } from 'react'

/**
 * Load the real corporación-municipal roster scraped from ribarroja.es.
 * Data is generated by `npm run scrape:officials` → public/data/officials.json.
 */
export function useOfficials() {
  const [state, setState] = useState({
    loading: true,
    error: null,
    data: null,
  })

  useEffect(() => {
    let cancelled = false
    fetch('/data/officials.json', { cache: 'no-cache' })
      .then((r) => {
        if (!r.ok) throw new Error(`officials.json returned ${r.status}`)
        return r.json()
      })
      .then((data) => {
        if (!cancelled) setState({ loading: false, error: null, data })
      })
      .catch((err) => {
        if (!cancelled) setState({ loading: false, error: err, data: null })
      })
    return () => {
      cancelled = true
    }
  }, [])

  return state
}

export const PARTY_COLORS = {
  PSOE: '#E8213A',
  PP: '#2463EB',
  VOX: '#63BE33',
  'Compromís': '#D4811E',
  Ciudadanos: '#F29F3C',
  Otro: '#8B5CF6',
}

export function partyColor(party) {
  return PARTY_COLORS[party] || '#64748B'
}
