#!/usr/bin/env tsx
/**
 * retract-guessed-attributions — migration: every `speakerGroup` produced by
 * the old content-inferring extractor → `null`.
 *
 *   npm run retract:guessed-attributions -- --dry-run   # report, write nothing
 *   npm run retract:guessed-attributions                # migrate
 *
 * WHY
 * ───
 * Until 2026-08-10 the claim extractor was asked which municipal group was
 * speaking, and answered from a ~1200-character window. Measured on pleno
 * 10yl550, of the 515 windows it sees:
 *
 *   ·   6 (1%)  contain a turn-grant — the only evidence of who holds the floor
 *   · 211 (41%) merely NAME a party, which in a debate is usually the party
 *               being attacked
 *   · 304 (59%) contain nothing bearing on speaker identity
 *
 * So the question was unanswerable from the input, and the model answered it
 * anyway by reaching for the party named in the text. The result is quotes
 * filed under the bloc they criticise — confirmed on 20 of 95 sampled rows,
 * and it is why EU-Podem, which holds a seat, appears in zero of 177 published
 * quotes.
 *
 * `speakerGroup` has since been removed from the extractor's schema entirely
 * (src/llm/schemas.ts) and is joined instead from `pleno-speaker-map/`, where
 * every speaker is backed by a cited turn-grant on tape. But the values the
 * old method already wrote are still on disk, and
 * `public/data/pleno-claims-suggestions.json` is 6.5 MB served by Vercel —
 * "no page renders it" is not "not published", which is the lesson of the 24
 * journalist drafts that sat web-fetchable for weeks.
 *
 * Replacing an unfounded attribution with `null` REMOVES a claim about a named
 * group rather than adding one: a weakening, Tier A in
 * src/scraper/automation-policy.ts, and the only direction
 * docs/DATA_INTEGRITY.md lets automation move a published verdict. Nothing
 * here ever sets a bloc; `null` is the value the UI already renders as «Grupo
 * no identificado» (src/lib/party-label.js).
 *
 * SCOPE — deliberately narrow
 * ───────────────────────────
 * Only object keys named exactly `speakerGroup`, whose value is a non-null
 * string, are rewritten. No verbatim, no verdict, no id, no timestamp, no
 * evidence. The run PROVES this by deep-comparing what it is about to write
 * against the parsed original put through the same single transform — if any
 * other byte would move, it aborts. Same guarantee, and the same shape, as
 * `retire-otro-sentinel.ts`.
 *
 * NOT IN SCOPE — `public/data/pleno-findings.json`. Those 113 attributions are
 * curated and published prose; retracting one leaves a public record via
 * `npm run correct-pleno-finding`, and which of them are actually wrong is a
 * question for the speaker map plus a curator, not a blanket pass. See
 * `src/scraper/attribution-reconcile.ts`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

/**
 * Machine-written snapshots only. Every one of these is regenerated by a
 * pipeline, so the migration is a shortcut for "re-run extraction", not an
 * edit to anything a human wrote.
 */
const TARGETS = ['pleno-claims-suggestions.json', 'auto-curation-bundles.json'] as const

type Json = unknown

/** Rewrite every non-null `speakerGroup` to null. Pure; returns a new tree. */
function retract(node: Json, tally: Record<string, number>): Json {
  if (Array.isArray(node)) return node.map((n) => retract(n, tally))
  if (!node || typeof node !== 'object') return node
  const out: Record<string, Json> = {}
  for (const [k, v] of Object.entries(node as Record<string, Json>)) {
    if (k === 'speakerGroup' && typeof v === 'string') {
      tally[v] = (tally[v] ?? 0) + 1
      out[k] = null
      continue
    }
    out[k] = retract(v, tally)
  }
  return out
}

function main() {
  const dryRun = process.argv.includes('--dry-run')
  let totalChanged = 0

  for (const name of TARGETS) {
    const path = resolve('public/data', name)
    const raw = readFileSync(path, 'utf8')
    const original = JSON.parse(raw)

    const tally: Record<string, number> = {}
    const migrated = retract(original, tally)
    const changed = Object.values(tally).reduce((a, b) => a + b, 0)

    // The proof. Re-derive from a SECOND independent parse and deep-compare:
    // if the transform touched anything but `speakerGroup`, these differ and
    // the run aborts rather than writing. A migration that cannot demonstrate
    // its own scope is a migration nobody can review.
    const control = retract(JSON.parse(raw), {})
    if (JSON.stringify(migrated) !== JSON.stringify(control)) {
      throw new Error(`${name}: transform is not deterministic — refusing to write`)
    }
    const back = JSON.parse(JSON.stringify(migrated))
    const stripped = (n: Json): Json => {
      if (Array.isArray(n)) return n.map(stripped)
      if (!n || typeof n !== 'object') return n
      const o: Record<string, Json> = {}
      for (const [k, v] of Object.entries(n as Record<string, Json>)) {
        o[k] = k === 'speakerGroup' ? null : stripped(v)
      }
      return o
    }
    if (JSON.stringify(stripped(original)) !== JSON.stringify(back)) {
      throw new Error(`${name}: something other than speakerGroup would move — refusing to write`)
    }

    const detail = Object.entries(tally)
      .sort((a, b) => b[1] - a[1])
      .map(([k, n]) => `${k} ${n}`)
      .join(' · ')
    process.stdout.write(
      `${dryRun ? '[dry-run] ' : ''}${name.padEnd(34)} ${String(changed).padStart(5)} retracted` +
        `${detail ? `  (${detail})` : ''}\n`,
    )
    totalChanged += changed

    if (!dryRun && changed > 0) {
      writeFileSync(path, JSON.stringify(migrated, null, 2) + '\n')
    }
  }

  process.stdout.write(
    `\n${dryRun ? 'Would retract' : 'Retracted'} ${totalChanged} attribution(s).\n` +
      `Every one becomes null. Nothing here can set a bloc.\n` +
      `pleno-findings.json is untouched on purpose — its 113 attributions are\n` +
      `published prose and go through correct-pleno-finding, one at a time.\n`,
  )
}

if (import.meta.url === `file://${process.argv[1]}`) main()

export { retract }
